//! S2O CyberMesh — WireGuard keys, conf generation, optional system wg status.

use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use clap::{Parser, Subcommand};
use colored::*;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use x25519_dalek::{PublicKey, StaticSecret};

#[derive(Parser)]
#[command(name = "cybermesh")]
#[command(author = "Split2ops Software <support@split2ops.com>")]
#[command(version = "0.3.0")]
#[command(about = "S2O CyberMesh: WireGuard keygen + config orchestration", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    Status,
    /// Print system `wg show` if available (does not create tunnels)
    Show,
    /// Attempt `wg-quick up` on a conf (requires admin + wg-quick)
    Up {
        #[arg(long, default_value = ".aegis/wg0.conf")]
        conf: PathBuf,
    },
    /// Attempt `wg-quick down`
    Down {
        #[arg(long, default_value = ".aegis/wg0.conf")]
        conf: PathBuf,
    },
    Peers,
    /// Real X25519 WireGuard-compatible keypair (base64)
    Genkey {
        #[arg(long)]
        write_private: Option<String>,
        #[arg(long)]
        write_public: Option<String>,
    },
    /// Derive public key from a base64 private key
    Pubkey {
        private_b64: String,
    },
    /// Write a WireGuard interface conf (for system wg-quick / import)
    Config {
        /// Output path
        #[arg(long, default_value = ".aegis/wg0.conf")]
        output: PathBuf,
        /// Interface address (CIDR)
        #[arg(long, default_value = "10.220.0.2/32")]
        address: String,
        /// Listen port (optional)
        #[arg(long)]
        listen_port: Option<u16>,
        /// DNS servers comma-separated (optional)
        #[arg(long)]
        dns: Option<String>,
        /// Path to private key file, or generate new
        #[arg(long)]
        private_key_file: Option<PathBuf>,
        /// Peer public key (base64)
        #[arg(long)]
        peer_public: Option<String>,
        /// Peer endpoint host:port
        #[arg(long)]
        peer_endpoint: Option<String>,
        /// AllowedIPs for peer
        #[arg(long, default_value = "10.220.0.0/24")]
        allowed_ips: String,
        /// PersistentKeepalive seconds
        #[arg(long, default_value_t = 25)]
        keepalive: u16,
    },
}

fn wg_keypair() -> (String, String) {
    let secret = StaticSecret::random_from_rng(rand_core::OsRng);
    let public = PublicKey::from(&secret);
    (B64.encode(secret.to_bytes()), B64.encode(public.as_bytes()))
}

fn wg_pubkey_from_private(private_b64: &str) -> Result<String, String> {
    let bytes = B64
        .decode(private_b64.trim())
        .map_err(|e| format!("base64 decode: {e}"))?;
    if bytes.len() != 32 {
        return Err(format!("private key must be 32 bytes, got {}", bytes.len()));
    }
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    let secret = StaticSecret::from(arr);
    let public = PublicKey::from(&secret);
    Ok(B64.encode(public.as_bytes()))
}

fn find_wg() -> Option<&'static str> {
    for bin in ["wg", "wg.exe"] {
        if Command::new(bin)
            .arg("version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            return Some(bin);
        }
    }
    None
}

fn find_wg_quick() -> Option<&'static str> {
    for bin in ["wg-quick", "wg-quick.exe"] {
        if Command::new(bin)
            .arg("--help")
            .output()
            .map(|o| o.status.success() || o.status.code().is_some())
            .unwrap_or(false)
        {
            // help often exits non-zero; existence via which-like: try running
            return Some(bin);
        }
    }
    // presence by path probe is weak; try spawn
    if Command::new("wg-quick").arg("help").output().is_ok() {
        return Some("wg-quick");
    }
    None
}

fn ensure_parent(path: &Path) -> std::io::Result<()> {
    if let Some(p) = path.parent() {
        fs::create_dir_all(p)?;
    }
    Ok(())
}

fn build_conf(
    private_key: &str,
    address: &str,
    listen_port: Option<u16>,
    dns: Option<&str>,
    peer_public: Option<&str>,
    peer_endpoint: Option<&str>,
    allowed_ips: &str,
    keepalive: u16,
) -> String {
    let mut conf = String::new();
    conf.push_str("# Generated by S2O CyberMesh - review before wg-quick up\n");
    conf.push_str("[Interface]\n");
    conf.push_str(&format!("PrivateKey = {private_key}\n"));
    conf.push_str(&format!("Address = {address}\n"));
    if let Some(port) = listen_port {
        conf.push_str(&format!("ListenPort = {port}\n"));
    }
    if let Some(dns) = dns {
        conf.push_str(&format!("DNS = {dns}\n"));
    }
    conf.push('\n');
    if let Some(pk) = peer_public {
        conf.push_str("[Peer]\n");
        conf.push_str(&format!("PublicKey = {pk}\n"));
        conf.push_str(&format!("AllowedIPs = {allowed_ips}\n"));
        if let Some(ep) = peer_endpoint {
            conf.push_str(&format!("Endpoint = {ep}\n"));
        }
        conf.push_str(&format!("PersistentKeepalive = {keepalive}\n"));
    } else {
        conf.push_str("# [Peer] section omitted — pass --peer-public / --peer-endpoint\n");
    }
    conf
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Status => {
            let wg = find_wg();
            let conf_path = PathBuf::from(".aegis/wg0.conf");
            println!(
                "{}",
                "=========================================================".cyan()
            );
            println!(
                "{}",
                "        S2O CyberMesh (Phase 3)                          "
                    .bold()
                    .green()
            );
            println!(
                "{}",
                "=========================================================".cyan()
            );
            println!(
                " system wg tool    : {}",
                if wg.is_some() {
                    format!("found ({})", wg.unwrap()).green().to_string()
                } else {
                    "not found (optional)".yellow().to_string()
                }
            );
            println!(
                " conf template     : {} ({})",
                conf_path.display(),
                if conf_path.exists() {
                    "present".green().to_string()
                } else {
                    "missing — cybermesh config".yellow().to_string()
                }
            );
            if let Some(bin) = wg {
                if let Ok(out) = Command::new(bin).arg("show").output() {
                    let text = String::from_utf8_lossy(&out.stdout);
                    if text.trim().is_empty() {
                        println!(
                            " Tunnel status     : {}",
                            "no interfaces (wg show empty)".yellow()
                        );
                    } else {
                        println!(
                            " Tunnel status     : {}",
                            "interfaces reported by wg show".green().bold()
                        );
                        for line in text.lines().take(12) {
                            println!("   {line}");
                        }
                    }
                }
            } else {
                println!(
                    " Tunnel status     : {}",
                    "unknown (install WireGuard tools to activate)".yellow()
                );
            }
            println!(
                " Implemented       : {}",
                "X25519 genkey/pubkey, conf writer, optional wg show / wg-quick".green()
            );
            println!(
                " Not implemented   : {}",
                "embedded boringtun userspace stack, auto mesh discovery".red()
            );
            println!(
                "{}",
                "=========================================================".cyan()
            );
        }
        Commands::Show => {
            let Some(bin) = find_wg() else {
                eprintln!("[cybermesh] `wg` not found on PATH");
                std::process::exit(2);
            };
            let status = Command::new(bin).arg("show").status()?;
            std::process::exit(status.code().unwrap_or(1));
        }
        Commands::Up { conf } => {
            if !conf.exists() {
                eprintln!(
                    "[cybermesh] conf missing: {} — run cybermesh config",
                    conf.display()
                );
                std::process::exit(1);
            }
            // Prefer wg-quick; on Windows WireGuard may use different tooling
            let iface = conf
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("wg0");
            if let Some(wq) = find_wg_quick() {
                println!("[cybermesh] running {wq} up {} ...", conf.display());
                let st = Command::new(wq).arg("up").arg(&conf).status()?;
                std::process::exit(st.code().unwrap_or(1));
            }
            eprintln!("[cybermesh] wg-quick not found.");
            eprintln!("Import {} with system WireGuard UI, or install wireguard-tools.", conf.display());
            eprintln!("Interface name hint: {iface}");
            std::process::exit(2);
        }
        Commands::Down { conf } => {
            if let Some(wq) = find_wg_quick() {
                let st = Command::new(wq).arg("down").arg(&conf).status()?;
                std::process::exit(st.code().unwrap_or(1));
            }
            eprintln!("[cybermesh] wg-quick not found — tear down via system WireGuard tools.");
            std::process::exit(2);
        }
        Commands::Peers => {
            if let Some(bin) = find_wg() {
                let out = Command::new(bin).args(["show", "all", "peers"]).output();
                match out {
                    Ok(o) if o.status.success() => {
                        let t = String::from_utf8_lossy(&o.stdout);
                        if t.trim().is_empty() {
                            println!("[cybermesh] no peers reported by wg");
                        } else {
                            print!("{t}");
                        }
                    }
                    _ => {
                        // fallback
                        let _ = Command::new(bin).arg("show").status();
                    }
                }
            } else {
                println!("[cybermesh] no peers — install WireGuard / run cybermesh config first.");
            }
        }
        Commands::Genkey {
            write_private,
            write_public,
        } => {
            let (privkey, pubkey) = wg_keypair();
            println!(
                "{}",
                "=========================================================".cyan()
            );
            println!(
                "{}",
                "  WireGuard X25519 keypair                               "
                    .bold()
                    .green()
            );
            println!(
                "{}",
                "=========================================================".cyan()
            );
            println!(" Private : {}", privkey.yellow());
            println!(" Public  : {}", pubkey.green());
            if let Some(path) = write_private {
                ensure_parent(Path::new(&path))?;
                fs::write(&path, format!("{privkey}\n"))?;
                println!(" Wrote private → {path}");
            }
            if let Some(path) = write_public {
                ensure_parent(Path::new(&path))?;
                fs::write(&path, format!("{pubkey}\n"))?;
                println!(" Wrote public  → {path}");
            }
        }
        Commands::Pubkey { private_b64 } => match wg_pubkey_from_private(&private_b64) {
            Ok(p) => println!("{p}"),
            Err(e) => {
                eprintln!("[cybermesh] {e}");
                std::process::exit(1);
            }
        },
        Commands::Config {
            output,
            address,
            listen_port,
            dns,
            private_key_file,
            peer_public,
            peer_endpoint,
            allowed_ips,
            keepalive,
        } => {
            let private_key = if let Some(pkf) = private_key_file {
                fs::read_to_string(&pkf)?.trim().to_string()
            } else {
                let (sk, pk) = wg_keypair();
                let key_path = output.with_extension("key");
                ensure_parent(&key_path)?;
                fs::write(&key_path, format!("{sk}\n"))?;
                let pub_path = output.with_extension("pub");
                fs::write(&pub_path, format!("{pk}\n"))?;
                println!("[cybermesh] generated keys:");
                println!("  private → {}", key_path.display());
                println!("  public  → {}", pub_path.display());
                sk
            };
            // validate
            if let Err(e) = wg_pubkey_from_private(&private_key) {
                eprintln!("[cybermesh] invalid private key: {e}");
                std::process::exit(1);
            }
            let conf = build_conf(
                &private_key,
                &address,
                listen_port,
                dns.as_deref(),
                peer_public.as_deref(),
                peer_endpoint.as_deref(),
                &allowed_ips,
                keepalive,
            );
            ensure_parent(&output)?;
            fs::write(&output, &conf)?;
            // restrict perms on unix
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let _ = fs::set_permissions(&output, fs::Permissions::from_mode(0o600));
            }
            println!(
                "{}",
                format!("[cybermesh] wrote {}", output.display())
                    .green()
                    .bold()
            );
            println!("Review the conf, then:");
            println!("  cybermesh up --conf {}", output.display());
            println!("  # or import into WireGuard for Windows");
        }
    }

    Ok(())
}
