[package]
name = "cyberedr"
version = "0.5.0"
edition = "2021"
authors = ["Split2ops Software"]

[[bin]]
name = "cyberedr"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
colored = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
s2o_net_lib = { path = "../../../net-lib" }
s2o-schema = { path = "../s2o-schema" }
s2o-store = { path = "../s2o-store" }
